---
- name: "{{ role_name }} | {{ ansible_distribution }} | Install browsers"
  community.general.pacman:
    name:
      - gtk4
    state: present
  become: true

- name: "{{ role_name }} | {{ ansible_distribution }} | Install AUR browsers"
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - rose-pine-gtk-theme-full
    state: present
  become: true
  become_user: aur_builder