---
- name: "{{ ansible_facts['distribution'] }} | Install Nautilus"
  community.general.pacman:
    name:
      - nautilus
    state: present
  become: true

- name: "{{ ansible_facts['distribution'] }} | Install Nautilus optional dependencies"
  community.general.pacman:
    name:
      # gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav
      - gstreamer
      - gst-plugins-base
      - gst-plugins-good
      - gst-plugins-bad
      - gst-plugins-ugly
      - gst-libav
      - gst-plugin-va
    state: present
  become: true

- name: "{{ ansible_facts['distribution'] }} | [AUR] Install nautilus-open-any-terminal"
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name: nautilus-open-any-terminal
    state: present
  become: true
  become_user: aur_builder

# https://github.com/Stunkymonkey/nautilus-open-any-terminal
- name: "{{ ansible_facts['distribution'] }} | Set Nautilus-open-any-terminal keybinding"
  community.general.dconf:
    key: "/com/github/stunkymonkey/nautilus-open-any-terminal/keybindings"
    value: "'<Ctrl><Alt>t'"
    state: present

- name: "{{ ansible_facts['distribution'] }} | Set Nautilus-open-any-terminal new-tab"
  community.general.dconf:
    key: "/com/github/stunkymonkey/nautilus-open-any-terminal/new-tab"
    value: "true"
    state: present

# - name: "{{ ansible_facts['distribution'] }} | Set Nautilus-open-any-terminal flatpak"
#   community.general.dconf:
#     key: "/com/github/stunkymonkey/nautilus-open-any-terminal/flatpak"
#     value: "'system'"
#     state: present
